server:
  port: 8082

spring:
  config:
    import: .env[.properties]
  application:
    name: review
  jackson:
    default-property-inclusion: NON_NULL
  r2dbc:
    url: r2dbc:postgresql://${DATASOURCE_HOST}:5432/review
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_HOST}

services:
  movie-url: ${MOVIE_URL}
